#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
通用计算引擎骨架（Generated by 智匠）
================================================
本文件由 智匠 自动生成，是“专家开发包”的核心组件。

使用方式：
  1. AI 会在下面的 TODO 占位符处填入你专业的计算公式。
  2. 你不需要修改通用部分（lookup_all、HTML 报告、主入口等）。
  3. 用 test_cases.json 里的标准算例验证，差异 ≤ 3% 即可部署。

结构速览：
  - LOOKUP_DATA   : 从 lookup_data.py 导入的查表数据
  - lookup_all()  : 通用查表函数（精确 / 最近 / 线性插值）
  - calc_mode_*() : 你的专属计算逻辑（TODO 区域）
  - build_html_report() : 统一报告格式
  - main()        : 外部调用入口（云函数、本地测试都用它）
"""

import json
import math
import os
import traceback
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

# ============================================================
# 1. 引入查表数据
# ============================================================
# 查表数据单独放在 lookup_data.py，方便你后续维护规范更新。
# 注意：所有内部路径统一用正斜杠 "/"，避免 Windows 反斜杠导致部署失败。
try:
    from lookup_data import LOOKUP_DATA
except ImportError as e:
    raise ImportError(
        "找不到 lookup_data.py。请确保它和 engine.py 在同一文件夹。"
    ) from e


# ============================================================
# 2. 通用工具函数
# ============================================================
def _as_float(value: Any) -> Optional[float]:
    """把用户输入转成浮点数；失败时返回 None，不抛异常。"""
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (ValueError, TypeError):
        return None


def _safe_get(d: Dict, key: str, default: Any = None) -> Any:
    """安全取字典值，兼容大小写和全半角差异。"""
    if key in d:
        return d[key]
    # 兼容首字母大写
    if key.capitalize() in d:
        return d[key.capitalize()]
    # 兼容全大写
    if key.upper() in d:
        return d[key.upper()]
    return default


def lookup_all(
    table_name: str,
    mode: str = "exact",
    warn_if_missing: bool = True,
    **keys: Any,
) -> Any:
    """
    通用查表函数。

    参数：
      table_name   : LOOKUP_DATA 里的表名
      mode         : 查表方式
                     - "exact"   精确匹配（默认值）
                     - "nearest" 最近匹配
                     - "interp"  线性插值（仅支持数值型单键）
      warn_if_missing : 数据缺失时是否打印警告（调试用）
      **keys       : 查询键值，例如 lookup_all("concrete_strength", grade="C30")

    返回：
      查到的值；找不到时返回 None。
    """
    if table_name not in LOOKUP_DATA:
        if warn_if_missing:
            print(f"[WARN] 查表失败：LOOKUP_DATA 中没有表 '{table_name}'")
        return None

    table = LOOKUP_DATA[table_name]

    # 精确匹配
    if mode == "exact":
        # 如果表是列表，逐项匹配所有键
        if isinstance(table, list):
            for row in table:
                if all(str(row.get(k, "")) == str(v) for k, v in keys.items()):
                    # 返回除了查询键之外的字段
                    return {k: v for k, v in row.items() if k not in keys}
            if warn_if_missing:
                print(f"[WARN] 精确查表失败：{table_name} 中无 {keys}")
            return None
        # 如果表是字典，按层级取
        if isinstance(table, dict):
            cur = table
            for k, v in keys.items():
                sv = str(v)
                if sv in cur:
                    cur = cur[sv]
                elif v in cur:
                    cur = cur[v]
                else:
                    if warn_if_missing:
                        print(f"[WARN] 字典查表失败：{table_name} 中无键 {k}={v}")
                    return None
            return cur

    # 最近匹配
    if mode == "nearest":
        # 只支持单键数值型
        if len(keys) != 1:
            raise ValueError("nearest 模式只支持单键查询")
        key_name, target = list(keys.items())[0]
        target = float(target)

        candidates = []
        if isinstance(table, list):
            for row in table:
                val = _as_float(row.get(key_name))
                if val is not None:
                    candidates.append((abs(val - target), row))
        elif isinstance(table, dict):
            for k, row in table.items():
                val = _as_float(k)
                if val is not None:
                    candidates.append((abs(val - target), row))

        if not candidates:
            if warn_if_missing:
                print(f"[WARN] 最近查表失败：{table_name} 中没有可用的 {key_name}")
            return None
        candidates.sort(key=lambda x: x[0])
        return candidates[0][1]

    # 线性插值
    if mode == "interp":
        if len(keys) != 1:
            raise ValueError("interp 模式只支持单键数值型查询")
        key_name, target = list(keys.items())[0]
        target = float(target)

        points = []
        if isinstance(table, list):
            for row in table:
                x = _as_float(row.get(key_name))
                y = _as_float(row.get("value"))
                if x is not None and y is not None:
                    points.append((x, y))
        elif isinstance(table, dict):
            for k, v in table.items():
                x = _as_float(k)
                y = _as_float(v)
                if x is not None and y is not None:
                    points.append((x, y))

        points.sort(key=lambda p: p[0])
        if not points:
            if warn_if_missing:
                print(f"[WARN] 插值失败：{table_name} 中没有可用的 {key_name}")
            return None

        # 小于最小值，取最小值；大于最大值，取最大值
        if target <= points[0][0]:
            return points[0][1]
        if target >= points[-1][0]:
            return points[-1][1]

        # 中间插值
        for i in range(len(points) - 1):
            x0, y0 = points[i]
            x1, y1 = points[i + 1]
            if x0 <= target <= x1:
                if x1 == x0:
                    return y0
                return y0 + (y1 - y0) * (target - x0) / (x1 - x0)

    raise ValueError(f"不支持的查表模式: {mode}")


# ============================================================
# 3. 你的专属计算逻辑（TODO：AI 会在这里填空）
# ============================================================
# 每个函数对应 SKILL.md 里的一个“模式”。
# 输入都是 params: dict，输出都是 result: dict。
# 请使用 lookup_all() 查表，不要直接把表格数据写进公式。


def calc_mode_a(params: Dict[str, Any]) -> Dict[str, Any]:
    """
    模式 A：请在这里填写你的第一个计算场景。

    示例（混凝土浇筑前裂缝预测）：
      - 输入：水泥品种、强度等级、水泥用量、浇筑温度...
      - 输出：最大绝热温升 T_max、综合温差 ΔT、抗裂安全系数 K

    TODO_BEGIN_MODE_A
    # 在这里写你的计算逻辑
    # 例如：
    # cement_type = params.get("cement_type")
    # grade = params.get("concrete_grade")
    # w_c = lookup_all("water_cement_ratio", grade=grade)["value"]
    # ...
    TODO_END_MODE_A
    """
    raise NotImplementedError("模式 A 的计算逻辑尚未填写。请让 AI 在 TODO 区域生成代码。")


def calc_mode_b(params: Dict[str, Any]) -> Dict[str, Any]:
    """
    模式 B：请在这里填写你的第二个计算场景（可选）。

    TODO_BEGIN_MODE_B
    TODO_END_MODE_B
    """
    raise NotImplementedError("模式 B 的计算逻辑尚未填写。若不需要，请在 SKILL.md 中移除该模式。")


def calc_mode_c(params: Dict[str, Any]) -> Dict[str, Any]:
    """
    模式 C：请在这里填写你的第三个计算场景（可选）。

    TODO_BEGIN_MODE_C
    TODO_END_MODE_C
    """
    raise NotImplementedError("模式 C 的计算逻辑尚未填写。若不需要，请在 SKILL.md 中移除该模式。")


def calc_mode_d(params: Dict[str, Any]) -> Dict[str, Any]:
    """
    模式 D：请在这里填写你的第四个计算场景（可选）。

    TODO_BEGIN_MODE_D
    TODO_END_D
    """
    raise NotImplementedError("模式 D 的计算逻辑尚未填写。若不需要，请在 SKILL.md 中移除该模式。")


# ============================================================
# 4. HTML 报告生成（通用，不要改）
# ============================================================

def _html_escape(text: Any) -> str:
    """防止 HTML 注入。"""
    s = str(text)
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def build_html_report(
    mode: str,
    params: Dict[str, Any],
    result: Dict[str, Any],
    warnings: List[str],
) -> str:
    """生成统一风格的 HTML 计算报告。"""
    rows = []
    for k, v in result.items():
        rows.append(f"<tr><td>{_html_escape(k)}</td><td>{_html_escape(v)}</td></tr>")

    params_rows = []
    for k, v in params.items():
        params_rows.append(f"<tr><td>{_html_escape(k)}</td><td>{_html_escape(v)}</td></tr>")

    warning_html = ""
    if warnings:
        lis = "".join(f"<li>{_html_escape(w)}</li>" for w in warnings)
        warning_html = f"""
        <div style="background:#fff3cd;border:1px solid #ffeeba;border-radius:4px;padding:12px;margin-bottom:16px;">
          <strong>⚠️ 提示</strong>
          <ul style="margin:8px 0 0 16px;padding:0;">{lis}</ul>
        </div>
        """

    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>计算报告</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 24px; color: #333; }}
    h2 {{ color: #1a1a1a; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }}
    table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
    th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
    th {{ background: #f5f5f5; }}
    .footer {{ margin-top: 24px; font-size: 12px; color: #888; }}
  </style>
</head>
<body>
  <h2>计算报告</h2>
  {warning_html}
  <p><strong>计算模式：</strong>{_html_escape(mode)}</p>
  <p><strong>生成时间：</strong>{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>

  <h3>输入参数</h3>
  <table>
    <tr><th>参数名</th><th>值</th></tr>
    {''.join(params_rows)}
  </table>

  <h3>计算结果</h3>
  <table>
    <tr><th>指标</th><th>值</th></tr>
    {''.join(rows)}
  </table>

  <div class="footer">
    本报告由 AI 专家自动生成，仅供参考。工程应用前请由专业工程师复核。
  </div>
</body>
</html>"""


# ============================================================
# 5. 主入口（通用，不要改）
# ============================================================

def main(payload: Dict[str, Any]) -> Dict[str, Any]:
    """
    外部统一入口。

    payload 格式：
    {
      "mode": "mode_a",           // 必填，对应 calc_mode_* 函数
      "params": { ... }            // 必填，用户输入的参数字典
    }

    返回格式：
    {
      "success": true,
      "mode": "mode_a",
      "result": { ... },
      "html_report": "<html>...</html>"
    }
    """
    try:
        mode = str(payload.get("mode", "")).strip().lower()
        params = payload.get("params", {})

        if not mode:
            return {"success": False, "error": "缺少 mode 参数"}
        if not isinstance(params, dict):
            return {"success": False, "error": "params 必须是字典"}

        # 映射到计算函数
        mode_map = {
            "mode_a": calc_mode_a,
            "mode_b": calc_mode_b,
            "mode_c": calc_mode_c,
            "mode_d": calc_mode_d,
        }

        if mode not in mode_map:
            return {
                "success": False,
                "error": f"不支持的 mode: {mode}。可选：{list(mode_map.keys())}",
            }

        calc_fn = mode_map[mode]
        result = calc_fn(params)

        # 收集警告信息（可在 calc_mode_* 里通过返回 warnings 字段携带）
        warnings = result.pop("warnings", []) if isinstance(result, dict) else []
        if not isinstance(warnings, list):
            warnings = []

        html_report = build_html_report(mode, params, result, warnings)

        return {
            "success": True,
            "mode": mode,
            "result": result,
            "html_report": html_report,
        }

    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc(),
        }


# ============================================================
# 6. 本地测试支持
# ============================================================
if __name__ == "__main__":
    # 示例：本地跑一个测试用例
    # 注意：mode_a 还没填计算逻辑时，会抛 NotImplementedError。
    test_payload = {
        "mode": "mode_a",
        "params": {
            # TODO：这里填一个真实测试用例的参数
            "example_param": "example_value",
        },
    }
    print(json.dumps(main(test_payload), ensure_ascii=False, indent=2))
