#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
通用查表数据骨架（Generated by 智匠）
================================================
本文件由 智匠 自动生成。

设计原则：
  1. 每个表都是 LOOKUP_DATA 字典的一个键。
  2. 表的格式优先用“列表 + 字典行”，方便维护和追加。
  3. 所有数值用原生数字（int/float），不要用字符串。
  4. 中文键名在 engine.py 里通过映射处理，不要在这里用中文键。

示例结构：
  LOOKUP_DATA = {
      "table_name": [
          {"grade": "C30", "value": 14.3},
          {"grade": "C35", "value": 16.7},
      ],
      "another_table": {
          "key1": {"sub_key": value},
      },
  }
"""

# ============================================================
# TODO：AI 会在这里填入你从规范中提取的查表数据。
# ============================================================
LOOKUP_DATA = {
    # 示例表：请删除或替换为真实数据
    "example_table": [
        {"key_a": "A1", "key_b": 10, "value": 1.23},
        {"key_a": "A1", "key_b": 20, "value": 1.45},
        {"key_a": "A2", "key_b": 10, "value": 2.34},
        {"key_a": "A2", "key_b": 20, "value": 2.56},
    ],

    # TODO_BEGIN_LOOKUP_DATA
    # 在这里添加更多查表数据
    # TODO_END_LOOKUP_DATA
}


# 可选：表的中文说明映射（用于报告展示）
TABLE_NAME_MAP = {
    "example_table": "示例查表",
    # TODO_BEGIN_TABLE_NAME_MAP
    # "your_table": "你的表中文名",
    # TODO_END_TABLE_NAME_MAP
}


def get_table_display_name(table_name: str) -> str:
    """获取表的中文展示名。"""
    return TABLE_NAME_MAP.get(table_name, table_name)
